# OpenAI Configuration
openai.api.key=${OPENAI_API_KEY}

# Google Cloud Vision (set this environment variable)
# GOOGLE_APPLICATION_CREDENTIALS=/path/to/your/service-account-key.json

# File Upload Settings
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# JPA Configuration
spring.application.name=duong
spring.datasource.url=jdbc:mysql://localhost:3306/englishapp?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Duong1997@
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true

# Gemini AP
gemini.api.key=${AIzaSyCmi2VNDXjBNxQMDnLh3M4VCgtPCnkrlHM}

# Pexels API
pexels.api.key=${FMDQnRLO1dcniUShjlqjANnjXYebgWymYkMEITJC3oXizVUS5liUQwwx}

# Voicerss API
voicerss.api.key=${723fe09017f84664bf678fb8006c2132}