spring:
  application:
    name: duong-app

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

logging:
  level:
    org.springframework.web: DEBUG
    org.springdoc: DEBUG

server:
  port: 8080